-
  branches:
    only:
    - nuget

  image: Visual Studio 2017

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install @types/node -global
    - npm install typescript -global
    - npm install ts-node -global
    - npm install @types/node --save

  before_build:
    - dotnet restore Ghpr.Core.sln

  build_script:
    - dotnet build Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\Tests.ps1

  on_finish:
  - ps: .\Coverage.ps1

  after_build:
    - dotnet pack "Ghpr.Core.Core/Ghpr.Core.csproj" /p:NuspecFile="Ghpr.Core.Core/Ghpr.Core.nuspec"

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

-
  branches:
    only:
    - nuget-localfilesystem

  image: Visual Studio 2017

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install @types/node -global
    - npm install typescript -global
    - npm install ts-node -global
    - npm install @types/node --save


  before_build:
    - dotnet restore Ghpr.Core.sln

  build_script:
    - dotnet build Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\Tests.ps1

  on_finish:
  - ps: .\Coverage.ps1

  after_build:
    - nuget pack "Ghpr.LocalFileSystem.Core/Ghpr.LocalFileSystem.csproj" -Prop Configuration=Release;OutDir=bin\Release;Platform=AnyCPU

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server:
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

-
  branches:
    only:
    - nuget-simplefilelogger

  image: Visual Studio 2017

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install @types/node -global
    - npm install typescript -global
    - npm install ts-node -global
    - npm install @types/node --save

  before_build:
    - dotnet restore Ghpr.Core.sln

  build_script:
    - dotnet build Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\Tests.ps1

  on_finish:
  - ps: .\Coverage.ps1

  after_build:
    - nuget pack "Ghpr.Logger.Core/Ghpr.SimpleFileLogger.csproj" -Prop Configuration=Release;OutDir=bin\Release;Platform=AnyCPU

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server:
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

-
  branches:
    except:
    - /nuget*/

  image: Visual Studio 2017

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install @types/node -global
    - npm install typescript -global
    - npm install ts-node -global
    - npm install @types/node --save

  before_build:
    - dotnet restore Ghpr.Core.sln

  build_script:
    - dotnet build Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\Tests.ps1

  on_finish:
  - ps: .\Coverage.ps1