-
  branches:
    only:
    - nuget

  image: Visual Studio 2017

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install @types/node -global
    - npm install typescript -global
    - npm install ts-node -global
    - npm install @types/node --save

  before_build:
    - nuget restore Ghpr.Core.sln

  build_script:
    - msbuild Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" "-targetargs:""Ghpr.Core.Tests\bin\Release\Ghpr.Core.Tests.dll""" -filter:"+[Ghpr.Core*]* -[Ghpr.Core.Tests*]*" -output:opencoverCoverage.xml

  on_finish:
  - ps: .\Coverage.ps1

  after_build:
    - nuget pack "Ghpr.Core/Ghpr.Core.csproj" -Prop Configuration=Release;OutDir=bin\Release

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

-
  branches:
    only:
    - nuget-localfilesystem

  image: Visual Studio 2017

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install @types/node -global
    - npm install typescript -global
    - npm install ts-node -global
    - npm install @types/node --save


  before_build:
    - nuget restore Ghpr.Core.sln

  build_script:
    - msbuild Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" "-targetargs:""Ghpr.Core.Tests\bin\Release\Ghpr.Core.Tests.dll""" -filter:"+[Ghpr.Core*]* -[Ghpr.Core.Tests*]*" -output:opencoverCoverage.xml

  on_finish:
  - ps: .\Coverage.ps1

  after_build:
    - nuget pack "Ghpr.LocalFileSystem/Ghpr.LocalFileSystem.csproj" -Prop Configuration=Release;OutDir=bin\Release;Platform=AnyCPU

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server:
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

-
  branches:
    only:
    - nuget-simplefilelogger

  image: Visual Studio 2017

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install @types/node -global
    - npm install typescript -global
    - npm install ts-node -global
    - npm install @types/node --save

  before_build:
    - nuget restore Ghpr.Core.sln

  build_script:
    - msbuild Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" "-targetargs:""Ghpr.Core.Tests\bin\Release\Ghpr.Core.Tests.dll""" -filter:"+[Ghpr.Core*]* -[Ghpr.Core.Tests*]*" -output:opencoverCoverage.xml

  on_finish:
  - ps: .\Coverage.ps1

  after_build:
    - nuget pack "Ghpr.Logger/Ghpr.SimpleFileLogger.csproj" -Prop Configuration=Release;OutDir=bin\Release;Platform=AnyCPU

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server:
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

-
  branches:
    only:
    - nuget-serilogtoseqlogger

  image: Visual Studio 2017

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install @types/node -global
    - npm install typescript -global
    - npm install ts-node -global
    - npm install @types/node --save


  before_build:
    - nuget restore Ghpr.Core.sln

  build_script:
    - msbuild Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" "-targetargs:""Ghpr.Core.Tests\bin\Release\Ghpr.Core.Tests.dll""" -filter:"+[Ghpr.Core*]* -[Ghpr.Core.Tests*]*" -output:opencoverCoverage.xml

  on_finish:
  - ps: .\Coverage.ps1

  after_build:
    - nuget pack "Ghpr.SerilogToSeq/Ghpr.SerilogToSeqLogger.csproj" -Prop Configuration=Release;OutDir=bin\Release;Platform=AnyCPU

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server:
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

-
  branches:
    except:
    - /nuget*/

  image: Visual Studio 2017

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install @types/node -global
    - npm install typescript -global
    - npm install ts-node -global
    - npm install @types/node --save

  before_build:
    - nuget restore Ghpr.Core.sln

  build_script:
    - msbuild Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" "-targetargs:""Ghpr.Tests.Tests\bin\Release\Ghpr.Core.Tests.dll""" -filter:"+[Ghpr.Core*]* -[Ghpr.Tests.Tests*]*" -output:opencoverCoverage.xml

  on_finish:
  - ps: .\Coverage.ps1