-
  branches:
    only:
    - nuget  

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  
  before_build:
    - nuget restore Ghpr.Core.sln

  build_script: 
    - msbuild Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - nuget pack "Ghpr.Core/Ghpr.Core.csproj" -Prop Configuration=Release;OutDir=bin\Release

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg
-
  branches:
    only:
    - nuget-localfilesystem  

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  
  before_build:
    - nuget restore Ghpr.Core.sln

  build_script: 
    - msbuild Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - nuget pack "Ghpr.LocalFileSystem/Ghpr.LocalFileSystem.csproj" -Prop Configuration=Release;OutDir=bin\Release;Platform=AnyCPU

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg
 -
  branches:
    only:
    - nuget-simnplefilelogger  

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  
  before_build:
    - nuget restore Ghpr.Core.sln

  build_script: 
    - msbuild Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - nuget pack "Ghpr.Logger/Ghpr.SimpleFileLogger.csproj" -Prop Configuration=Release;OutDir=bin\Release;Platform=AnyCPU

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg
 -
  branches:
    only:
    - nuget-serilogtoseqlogger  

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  
  before_build:
    - nuget restore Ghpr.Core.sln

  build_script: 
    - msbuild Ghpr.Core.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - nuget pack "Ghpr.SerilogToSeq/Ghpr.SerilogToSeqLogger.csproj" -Prop Configuration=Release;OutDir=bin\Release;Platform=AnyCPU

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg
    
-
  branches:
    only:
    - master

  install:
    - ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  before_build:
    - nuget restore Ghpr.Core.sln

  build_script: 
    - msbuild Ghpr.Core.sln /p:Configuration=Release /t:Rebuild
